# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addr',
            field=models.CharField(help_text='올바른 우편번호를 입력하시오.', max_length=200, validators=[post.models.postal_code_validator]),
        ),
    ]
