# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pokemon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnt', models.IntegerField(default=0, max_length=20)),
                ('monster', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=20)),
                ('num', models.IntegerField(max_length=20)),
                ('position', models.CharField(help_text='x,y 포맷으로 입력', max_length=30, validators=[pokemon.models.position_validator])),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Human')),
            ],
        ),
        migrations.AddField(
            model_name='catch',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Human'),
        ),
        migrations.AddField(
            model_name='catch',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemon'),
        ),
    ]
