# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20160718_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='position',
        ),
        migrations.AddField(
            model_name='catch',
            name='position',
            field=models.CharField(default=(0, 0), help_text='x,y 포맷으로 입력', max_length=30, validators=[pokemon.models.position_validator]),
            preserve_default=False,
        ),
    ]
