# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20160719_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='master',
        ),
        migrations.RemoveField(
            model_name='human',
            name='monster',
        ),
        migrations.AddField(
            model_name='human',
            name='monster',
            field=models.ManyToManyField(to='pokemon.Pokemon'),
        ),
    ]
